### ISSUE TITLE
Transfer your notes into the GitHub wiki

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#1]
Not necessarily all of them, but anything that may be useful to the "general research team", including but not limited to:
* What browsers are we using and why?
* What versions are we using and why?
* Where did you find the information on browser releases?
* What external software are we using? (OneGet, Chocolatey, ...)

Let's try to keep it short and structured (bullet points often work good).

**Comment by filipgontko-zz** [comment]
Some notes are already there. I will work with the documentation a little bit more.

**Comment by filipgontko-zz** [comment]
This should be done for all notes I have so far. More will be added as we move on.
