### ISSUE TITLE
Local installation of browsers

### ISSUE THREAD

**Issue by filipgontko-zz** [crocs-muni/tls-warning-collector#10]
Check how chocolatey installs files in order to know how to install browsers locally.

**Comment by filipgontko-zz** [comment]
`Start-Process -Wait -FilePath "path-to-chromium" -ArgumentList "/S --do-not-launch-chrome" -PassThru`
This code works for installation of chromium from exe.

**Comment by mukrop** [comment]
The wisdom from this issue can be written to an appropriate wiki section and issue probably closed.

**Comment by filipgontko** [comment]
Information added to Known issues wiki section.
