### ISSUE TITLE
Add project metadata to repo

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#14]
To let people visiting our repository understand what we do, some metadata should be added.
* Repo description and tags (in page header below repo name).
* Short research description at the beginning of the Readme file.
* Authors and lab attribution in the Readme file (see e.g. https://github.com/crocs-muni/eacirc).

Take some time formulating the short description -- think of it as an abstract: it should explain shortly what is the problem we are tackling, what we are doing and how we are doing it.

**Comment by filipgontko-zz** [comment]
Authors added and short description as well. Need to add short research description at the beginning of the readme file.

**Comment by mukrop** [comment]
Also add a (prominent) link to the wiki into the `README.md` file (browsing the project, I would almost not notice the wiki is used).

**Comment by mukrop** [comment]
Great, done in my view.
