### ISSUE TITLE
Cleanup the Main.ps1 code

### ISSUE THREAD

**Issue by filipgontko-zz** [crocs-muni/tls-warning-collector#15]
Delete all unnecessary things from the code.

**Comment by filipgontko-zz** [comment]
Code is almost clean. There are only few versions commented out for test purposes.

**Comment by mukrop** [comment]
Clean out the comments as well, please. These should be either in the Readme or in the wiki.

**Comment by filipgontko-zz** [comment]
PS code won't be used anymore.
