### ISSUE TITLE
Add Windows deployment (?)

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#17]
How complicated is the current configuration of the project? If it's not extra-complicated, I suggest having a deploy phase set up (an automatic Windows VM that runs the script to see it at least exists successfully). For deployment, [AppVeyor](https://www.appveyor.com/) should be a good match.

I'm not sure if you have any prior experience deploying a CI. Some inspiration can be found in CRoCS CI demo: https://github.com/crocs-muni/git-ci-demo

**Comment by filipgontko-zz** [comment]
I don't have experience of deploying my own CI. But I have been working with automatic setup of VM's in OpenStack. I prepared a yaml file where I specified what has to be done when the machine starts up for the first time. So I think it should be almost the same, shouldn't it?

**Comment by mukrop** [comment]
Yes, it sounds similar enough.
What I'm not sure about OpenStack: Can you spin up the machine for free
(reasonably)?
The idea of ApoVeyor is to run an automatic (!) test built automatically at
every (or just selected) push. It's also configured via an YML file, I
guess it's pretty similar to OpenStack.

**Comment by filipgontko-zz** [comment]
OpenStack is paid but I don't think it is the best choice for CI. The AppVeyor seems very reasonable but it is paid as well.

**Comment by mukrop** [comment]
AppVeyor is free for open source projects as far as I know.
I've enabled the build (
https://ci.appveyor.com/project/mathius/tls-warning-collector) and it seems
to work.
Have a look at the yml config, I really think the necessary adjustments
will be minimal (if there are not small, let me know and we can discuss
whether to go for it or not).

Martin.

**Comment by filipgontko-zz** [comment]
Try just a simple version which will try to install it and run one case and one browser version.

**Comment by mukrop** [comment]
I guess this will not be done? If not, let's close the issue.

**Comment by filipgontko** [comment]
This won't be done now. Closing.
