### ISSUE TITLE
Create issues for your planned work

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#2]
Try to chunk your work into issues here. We have currently planned a couple of different things to do, let's keep it organized.

Think about labels, milestones, projects (GitHub-provided infrastructure in issues) and use what you see as useful for the project (depends also on your job workflow I guess). Let's not overcomplicate it -- use only what you consider useful (or start using it when it becomes useful).

**Comment by filipgontko-zz** [comment]
Issues are created.

**Comment by mukrop** [comment]
Good job, it has a much more transparent structure now!
