### ISSUE TITLE
General troubleshooting thread

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#29]
I'm unable to run the browsers as the drivers are inaccessible. It seems the driver version is not set correctly in the driver path (see log below).

Connected to that:
* What should be the content of the `drivers` folder? Should it be the three folders `chrome/firefox/operadrivers`? Or should I copy these things out as well? (I tried both.)
* Is it really necessary to add the drivers folder to the PATH (as it seems every browser version seems to set it itself separately due to different drivers)?

Note that the script worked some -- I generated a couple of screenshots in one run, but from then on this bug seems to occur all the time. If I resolve it, I'll update the issue.

```
08-Sep-19 21:41:32 - INFO - ######## Processing firefox v(64.0)
08-Sep-19 21:41:32 - INFO - # Installing the browser.
08-Sep-19 21:42:02 - INFO - # Installation done.
08-Sep-19 21:42:02 - INFO - # Preparing iteration.
08-Sep-19 21:42:02 - INFO - ##################################################
08-Sep-19 21:42:02 - INFO -                                                   
08-Sep-19 21:42:02 - INFO -            firefox 64.0 expired         
08-Sep-19 21:42:02 - INFO -                                                   
08-Sep-19 21:42:02 - INFO - ##################################################
08-Sep-19 21:42:02 - INFO - Preparing driver path.
08-Sep-19 21:42:02 - INFO - Driver path set to - C:\Users\Username\Documents\tls-warning-collector\drivers\firefoxdrivers\geckodriver-
08-Sep-19 21:42:02 - INFO - Parsing browser full version to short.
08-Sep-19 21:42:02 - INFO - Browser short version - 64
08-Sep-19 21:42:02 - INFO - Getting geckodriver version.
08-Sep-19 21:42:02 - INFO - Geckodriver version - 24.
08-Sep-19 21:42:02 - INFO - Capabilities are set to - {'marionette': True}
08-Sep-19 21:42:02 - INFO - Preparing driver.
08-Sep-19 21:42:02 - ERROR - Something went TERRIBLY wrong. - Message: 'geckodriver.exe',)' executable needs to be in PATH. 
```

**Comment by filipgontko-zz** [comment]
It happened to me as well sometimes. I will try to fix it with setting the SystemProperty each time before the driver is used.
`System.setProperty("webdriver.gecko.driver", "path/to/geckodriver.exe");`
`System.setProperty("webdriver.chrome.driver", "path/to/opera-or-chromiumdriver.exe");` -- for both Chromium and Opera

Will try with Python alternative using os.path

**Comment by mukrop** [comment]
Uff, after some time spend debugging I see the culprit.
In `browesrs.py` on line 114 there is an extra comma that causes the `exe` variable to be defined as a tuple instead of a string.

The bug was introduced in commit 625f314 26 days ago -- did it work for you since then?

**Comment by mukrop** [comment]
Though running it now, I get other errors:
* Some firefox/error combinations work OK (e.g. FF64/expired).
* Sometimes (e.g. FF64/wrong-host) I get: `ERROR - Something went TERRIBLY wrong. - Message: Reached error page: about:neterror?e=fileNotFound&u=https%3A//wrong-host.badssl.com/&c=UTF-8&f=regular&d=Firefox%20can%27t%20find%20the%20file%20at%20https%3A//wrong-host.badssl.com/`
* Sometimes (e.g. FF63/expired): `ERROR - Something went TERRIBLY wrong. - Message: Unable to find a matching set of capabilities` (though when I simply re-run this, it passed)

Did all the cases, browsers and versions pass for you as written in the documentation?

**Comment by filipgontko-zz** [comment]
All of these issues should be resolved now.
