### ISSUE TITLE
Summarise known and unresolved exceptions

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#3]
Create "bug" issues for the Firefox/Opera/Explorer/... issues discussed (the problems in particular versions) so that they won't get forgotten.

Maybe a separate issue per browser and summarise all browser issues in it? Find the way that suits you.

**Comment by mukrop** [comment]
Is this not already done?

**Comment by filipgontko-zz** [comment]
You are right. I forgot to close the issue so I'm closing now.
