### ISSUE TITLE
Firefox: OS reboot required

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#30]
For some FF versions I'm getting a message requesting OS reboot to complete the FF upgrade/downgrade. Did you also get this? Do we know what does it cause if I don't reboot? (I did not reboot yet.)

**Comment by filipgontko-zz** [comment]
I don't get this message. I only get a message saying that I should decide in 30 seconds whether I want to uninstall it silently or not. If you do nothing, it will automatically choose.
