### ISSUE TITLE
Multiple browsers don't get uninstalled

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#31]
After running the whole script for Firefox, Chrome, Chromium and Opera with all the versions and the 9 cases currently in the config (for the record: runtime cca 3 hours), I have Chrome (v76), Chromium (v61) and Firefox (v15) still installed on the system (so the uninstallation failed somewhere). The versions may not be relevant as some browsers have rather aggressive auto-update.

Is this a consistent behavior? Do we know what versions have trouble uninstalling (and why)? Are they installed in a substandard location? I would have expected the cleaning step (deleting the folders after use) gets them not functional even if they fail to uninstall.

**Comment by filipgontko-zz** [comment]
I prolonged the wait also for uninstall and the removal of files is done after the uninstallation. Should be fixed.
