### ISSUE TITLE
Opera binary not found?

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#32]
After running the whole set, I don't get any screenshots from Opera. The browser was never run as the binary seems not to be found:
`ERROR - Something went TERRIBLY wrong. - Message: unknown error: no Opera binary at C:\Users\IEUser\AppData\Local\Programs\Opera\58.0.3135.118\opera.exe
  (Driver info: OperaDriver=2.42.3135 (O58),platform=Windows NT 10.0.18362 x86_64)`

Any idea what this may be caused by?

**Comment by filipgontko-zz** [comment]
That is strange because this happened to me mostly when the Opera was not uninstalled properly. After I did the uninstallation manually it worked as it should.

**Comment by filipgontko-zz** [comment]
It is happening when there is not correctly uninstalled previous version.
