### ISSUE TITLE
Chrome/chromium driver difference?

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#33]
After running the whole set, I have plenty of screenshots from Chromium but none from Chrome. In the log, I see Chrome was never run and complained about the driver.
`ERROR - Something went TERRIBLY wrong. - Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

Don't they both use the same driver?

**Comment by mukrop** [comment]
As for chromium -- even though I did get some screenshots, for others I get these:
* Older versions: `ERROR - Something went TERRIBLY wrong. - ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))`
* For example version 66: `ERROR - Something went TERRIBLY wrong. - Message: unknown error: no chrome binary at C:\Program Files (x86)\Chromium\Application\chrome.exe
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.18362 x86_64)`

**Comment by filipgontko** [comment]
Chrome browser is not in the final dataset. Closing issue.
