### ISSUE TITLE
Logging philosophy

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#34]
What is the current philosophy of the logger? The output of the logger in the file is extremely useful (thanks for that!).
The PowerShell console has the output from Chocolatey -- which means if the running fails I don't know it (as it's in the file log). Would it be possible to have the content of the file also as a terminal log? (I find it much more useful than the Chocolatey log.)

**Comment by filipgontko-zz** [comment]
I will look into it and I could try to have both, the output in the folder and on the output as well.

**Comment by filipgontko-zz** [comment]
The output is done both ways. It is logged into a logfile and displayed at the output as well.
