### ISSUE TITLE
Milestone: Lydia generates the dataset

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#4]
I propose a milestone @filipgontko, at the latest till the end of August. Let's get the software and the documentation to a point that Lydia will be able to clone the repo and run the software to obtain the dataset. (And, ideally, configure the basics of which parts of the dataset she wants.)

**Comment by mukrop** [comment]
Can we get here till the summer ends?

**Comment by filipgontko-zz** [comment]
We can but there won't be all versions I suppose. There are still issues with versions with alert messages. I don't know why the opera does not accept send_keys(). Well it does but only TAB so far. Maybe some other as well but not arrow keys, RETURN, ALT and F* buttons.

**Comment by mukrop** [comment]
I'm OK with not supporting everything yet. I'd just like to prototype-test
the tool rather early to see if it goes the right (=useful) direction.

**Comment by filipgontko-zz** [comment]
Yes that I understand and it will be ready to work with versions I can run right now.

**Comment by filipgontko-zz** [comment]
I think we can close this and on the Hackathon we can set a new milestone.
