### ISSUE TITLE
AllowSslCerts - Chrome-based

### ISSUE THREAD

**Issue by filipgontko-zz** [crocs-muni/tls-warning-collector#57]
Chrome-based browsers have problems with the desired_capability called "allowSslCerts".You can set it to False but afterwards it is set to True by default. This cannot be changed by me. It has to be allowed or changed by the team standing behind the Chrome webdriver. Already contacted them. If I get new info, I will write it here.

**Comment by mukrop** [comment]
Hm, Im not sure I understand. What is `allowSslCerts` good for?

**Comment by filipgontko-zz** [comment]
It is essential capability for browsers to not accept SSL warnings by default. So if it is set to True, it will not show us the warning. If it is False, it will show the warning on the website.

**Comment by mukrop** [comment]
I see, That is indeed rather important.
