### ISSUE TITLE
Offline installer for Chrome

### ISSUE THREAD

**Issue by filipgontko-zz** [crocs-muni/tls-warning-collector#7]
Find out if it is possible to get and offline installer for Chrome and try to test it fully offline.

**Comment by filipgontko-zz** [comment]
At Neowin there are offline installation files of multiple Google Chrome versions.
https://www.neowin.net/news/google-chrome-6503325181/
I tried to install them but the installation is not working. The installation files starts to run but then does nothing.

**Comment by filipgontko** [comment]
Offline installer option was not working for me. Closing this issue.
