### ISSUE TITLE
Configuration of project

### ISSUE THREAD

**Issue by filipgontko-zz** [crocs-muni/tls-warning-collector#8]
Think about being able to configure the project and how it would work. Start developing some ideas and try them.

**Comment by filipgontko-zz** [comment]
I had an idea that there would be questions asked and user would answer them with numbers.
Eg. Which browsers would you like to try? (Choose 1-5)
1 - Firefox
2 - Chromium
3 - Chrome
4 - Opera
5 - All
Browser choice: 5 (if you want all)
And like this it would work for cases as well.

**Comment by mukrop** [comment]
I'm OK with interactive configuration if you want but please also support an un-interactive alternative as well (e.g. setting it with CLI arguments or a config file).
* Interactivity is friendly for users.
* But unfriendly for developers. Imagine yourself debugging the script and having to go through the four interactive steps every time...

**Comment by filipgontko-zz** [comment]
I understand that is correct. So basically I could do both.

**Comment by filipgontko-zz** [comment]
config.yaml created and python can read it. Not tested if its fully working yet.

**Comment by filipgontko-zz** [comment]
config.yaml works
